package com.mauro.nfl.domain.position;

public enum Role {
    POCKET_PASSER, MOBILE, GUNSLINGER,
    ELUSIVE_BACK, POWER_BACK, RECEIVING_BACK, ONE_CUT, THIRD_DOWN,
    BLOCKER, SHORT_YARDAGE, RECEIVER,
    PASS_BLOCK, RUN_BLOCK,
    X_RECEIVER, Y_RECEIVER, Z_RECEIVER, SLOT,
    PLACEKICKER, KICKOFF,
    PUNTER,
    KICK_RETURNER, PUNT_RETURNER,
    LONG_SNAPPER,
    RUN_STOPPER, RUSHER,
    BLITZER, GENERAL, COVERAGE, TACKLER,
    OUTSIDE, SLOT_CB,
}
